# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 12:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0002_auto_20171114_2006'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
        migrations.DeleteModel(
            name='Skill_type',
        ),
    ]
