# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0004_blog_skill_skill_type_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='cookile',
            field=models.CharField(default='无', max_length=50),
        ),
        migrations.AlterField(
            model_name='users',
            name='is_root',
            field=models.IntegerField(default=0, max_length=2),
        ),
        migrations.AlterField(
            model_name='users',
            name='loginip',
            field=models.CharField(default='NULL', max_length=20),
        ),
        migrations.AlterField(
            model_name='users',
            name='logintime',
            field=models.CharField(default='NULL', max_length=20),
        ),
        migrations.AlterField(
            model_name='users',
            name='state',
            field=models.IntegerField(default=1, max_length=2),
        ),
        migrations.AlterField(
            model_name='users',
            name='true_name',
            field=models.CharField(default='无', max_length=20),
        ),
    ]
