# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 03:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0005_auto_20171114_2031'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='content',
            new_name='editorValue',
        ),
        migrations.RenameField(
            model_name='skill',
            old_name='content',
            new_name='editorValue',
        ),
        migrations.AlterField(
            model_name='blog',
            name='autor',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='blog',
            name='clicks',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='blog',
            name='state',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='blog',
            name='thumbnail',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='autor',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='skill',
            name='classify',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='skill',
            name='clicks',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='skill',
            name='state',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='skill',
            name='thumbnail',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='cookile',
            field=models.CharField(default='NULL', max_length=50),
        ),
        migrations.AlterField(
            model_name='users',
            name='is_root',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='users',
            name='state',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='users',
            name='true_name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
