# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 03:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0006_auto_20171115_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='thumbnail',
            field=models.CharField(default='NULL', max_length=254),
        ),
    ]
