# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0008_auto_20171115_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='createtime',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
