# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 03:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0012_auto_20171115_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='createtime',
            field=models.DateTimeField(default='2017-11-16 11:29:09'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='updatetime',
            field=models.DateTimeField(default='2017-11-16 11:29:09'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='createtime',
            field=models.DateTimeField(default='2017-11-16 11:29:09'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='updatetime',
            field=models.DateTimeField(default='2017-11-16 11:29:09'),
        ),
    ]
