# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0013_auto_20171116_1129'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('tid', models.IntegerField()),
                ('group', models.CharField(max_length=10)),
                ('fid', models.IntegerField()),
                ('content', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='blog',
            name='createtime',
            field=models.DateTimeField(default='2017-11-17 20:48:19'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='updatetime',
            field=models.DateTimeField(default='2017-11-17 20:48:19'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='createtime',
            field=models.DateTimeField(default='2017-11-17 20:48:19'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='updatetime',
            field=models.DateTimeField(default='2017-11-17 20:48:19'),
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(max_length=50),
        ),
    ]
