# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0016_auto_20171117_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='articleid',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='blog',
            name='createtime',
            field=models.DateTimeField(default='2017-11-17 20:58:33'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='updatetime',
            field=models.DateTimeField(default='2017-11-17 20:58:33'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='time',
            field=models.DateTimeField(default='2017-11-17 20:58:33'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='createtime',
            field=models.DateTimeField(default='2017-11-17 20:58:33'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='updatetime',
            field=models.DateTimeField(default='2017-11-17 20:58:33'),
        ),
    ]
