# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0017_auto_20171117_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='createtime',
            field=models.DateTimeField(default='2017-11-17 21:34:08'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='updatetime',
            field=models.DateTimeField(default='2017-11-17 21:34:08'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='articleid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='reply',
            name='time',
            field=models.DateTimeField(default='2017-11-17 21:34:08'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='createtime',
            field=models.DateTimeField(default='2017-11-17 21:34:08'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='updatetime',
            field=models.DateTimeField(default='2017-11-17 21:34:08'),
        ),
    ]
